[package]
name = "coinflip"
version = "0.1.0"
authors = ["garritfra <garritfranke@gmail.com>"]
edition = "2018"
description = "Flip a coin and test your luck🔮"
license = "MIT"

[dependencies]
rand = "0.6.5"